### ISSUE TITLE
missing `handlers/main.yml` ?

### ISSUE THREAD

**Issue by gsaslis** [geerlingguy/turing-pi-2-cluster#10]
Hey @geerlingguy, 

I'm not sure if I'm reading the below error correctly, but I tried to use this repo to set up a new cluster of raspberry pis with k3s ( I ran into some issues with `k3s-io/k3s-ansible` ) and when I try to use this, I get a weird issue: 

```bash
$ ansible-playbook main.yml
ERROR! Unable to retrieve file contents
Could not find or access '<redacted>/turing-pi-2-cluster/handlers/main.yml' on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option
```

It seems like this was introduced with 98cfce5d1eb413aab504b95ea606318a46fa5457 ?

**Comment by gsaslis** [comment]
I should add that after commenting those `import_tasks` lines out, I was able to run the playbook.

**Comment by geerlingguy** [comment]
@gsaslis yeah, oops! I just have https://github.com/geerlingguy/turing-pi-2-cluster/blob/98cfce5d1eb413aab504b95ea606318a46fa5457/main.yml#L7-L9 for now, so I can drop those other imports for the missing handlers file. Will fix in a moment.
