### ISSUE TITLE
Adding nodes to the k3s cluster

### ISSUE THREAD

**Issue by gsaslis** [geerlingguy/turing-pi-2-cluster#18]
Hi there, 

I started with a single pi, using it as both a `control_plane` and a regular `node`. I ran the playbook and I got k3s running. 

I then got another pi, prepared the SD card, and once SSH was configured, I added its IP address to both groups (`control_plane` and `nodes` ). I ran the playbook and it ran to completion without any obvious errors. 

However, I cannot see the 2nd node joining the k3s cluster... 🤔

```console
$ kubectl get node
NAME             STATUS   ROLES                  AGE   VERSION
raspberrypi4-0   Ready    control-plane,master   27d   v1.22.5+k3s1
```

Is this a valid scenario that should be supported? Or will the setup only work if both raspberries are installed at the same time ? Or is it not expected that a pi will be part of both groups (control_plane and nodes) ?

Thanks in advance!

**Comment by gsaslis** [comment]
Hmmm... I was able to add the 2nd worker node (btw - how about renaming `nodes` group to `workers` ? ) to the cluster, but not a 2nd control plane node. 

The k3s logs (`journalctl -u k3s`) revealed some TLS-related errors: `remote error: tls: bad certificate`

When removing the 2nd pi from the `control_plane` group, uninstalling k3s with `/usr/local/bin/k3s-killall.sh && /usr/local/bin/k3s-uninstall.sh` and rerunning the playbook, the worker was added to the cluster.

**Comment by geerlingguy** [comment]
@gsaslis - This playbook doesn't explicitly support adding multiple nodes to the `control_plane` (right now it's only structured for a single controller). See this upstream issue for some ideas for multi-master/multi-controller K3s setup with Ansible: https://github.com/k3s-io/k3s-ansible/issues/32

**Comment by gsaslis** [comment]
@geerlingguy ok thanks a lot! I'll go take a look there!
